version: '3'
services:
  db:
    build: ./db
    ports:
      - "5433:5432"
    networks:
      - tradesnetwork

  jupyter:
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./02_data_platform/jupyter/output:/home/jovyan/work/
    networks:
      - tradesnetwork

networks:
  tradesnetwork:
