version: '3'
services:
  db:
    build: ./db
    ports:
      - "5433:5432"
    networks:
      - tradesnetwork

  jupyter:
    depends_on:
      - db
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/output:/home/jovyan/work/
    networks:
      - tradesnetwork

  dbt:
    depends_on:
      - db
    build: ./dbt
    ports:
      - "80:80"
    volumes:
      - ./dbt/dbt_trades:/home/app/
    networks:
      - tradesnetwork

networks:
  tradesnetwork:
