version: '3'
services:
  db:
    build: ./db
    ports:
      - "5433:5432"
    volumes:
      - ./db/data:/home/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - tradesnetwork

  jupyter:
    depends_on:
      - db
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/output:/home/jovyan/work/
    networks:
      - tradesnetwork

  dbt:
    depends_on:
      - db
    build: ./dbt
    ports:
      - "8080:8080"
    volumes:
      - ./dbt/dbt_trades:/home/app/
    networks:
      - tradesnetwork

  airflow:
    user: "${AIRFLOW_UID:-50000}:${DOCKER_GID:-1001}"
    environment:
      - AIRFLOW_USERNAME=${AIRFLOW_USERNAME}
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}
      - AIRFLOW_FIRSTNAME=${AIRFLOW_FIRSTNAME}
      - AIRFLOW_LASTNAME=${AIRFLOW_LASTNAME}
      - AIRFLOW_ROLE=${AIRFLOW_ROLE}
      - AIRFLOW_EMAIL=${AIRFLOW_EMAIL}
      - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/dags
      - DOCKER_URL=${DOCKER_URL}
    build: ./airflow
    ports:
      - "8090:8080"
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/output:/usr/local/airflow/output
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    command: airflow standalone
    networks:
      - tradesnetwork

networks:
  tradesnetwork: